hooks
style 
	^ '
.navbar-brand { 
	text-transform: uppercase;
	font-weight: 600;
	font-size: 22px;
	color: white;
}
ul.nav li a { 
	text-transform: uppercase;
	font-size: 20px;
}
.right { 
	float: right;
}
.head { 
	border-bottom: 1px solid gray;
}
.control-label { 
	font-size: 18px;
	font-weight: 300;
}
.login-form {  
	margin-top: 100px;
	padding: 20px 0 20px 0;
	border: 1px solid lightgray;
	border-radius: 10px;
}
.register-header {  
	margin: 0 0 30px 30px;
}
.form-header {  
	border-bottom: 1px solid gray;
}
input .form-control {  
	padding: 15px;
	line-height: 20px;
}
.login-button {
	margin-top: 20px;
	margin-left: 10px;  
	font-size: 20px;
	font-weight: 300;
}
'